= API 문서
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

= 회원(Member)

== 회원 생성

=== request

operation::member-controller-test/create-member[snippets='http-request,request-fields']

=== response

operation::member-controller-test/create-member[snippets='http-response,response-fields']

= 공연(Performance)

= 장소(Place)

= 좌석(Seat)

== 관리자 좌석 등급 생성 API

=== request

operation::admin-seat-controller-test/create-seat-grades[snippets='http-request,path-parameters,request-fields']

=== response

operation::admin-seat-controller-test/create-seat-grades[snippets='http-response']

== 관리자 좌석 생성 API

=== request

operation::admin-seat-controller-test/create-seats[snippets='http-request,path-parameters,request-fields']

=== response

operation::admin-seat-controller-test/create-seat-grades[snippets='http-response']

= 티켓(Ticket)

= API 문서화 예시

== GET 문서화

=== request

operation::documentation-test/get-docs[snippets='http-request,query-parameters']

=== response

operation::documentation-test/get-docs[snippets='http-response,response-fields']

== POST 문서화

=== request

operation::documentation-test/post-docs[snippets='http-request,path-parameters,request-fields']

=== response

operation::documentation-test/post-docs[snippets='http-response,response-fields']
